/**
 * JustWatch provider identifiers aligned with Partner API field names (technical_name, short_name, clear display name).
 *
 * **Scope:** United States only — extrapolated from the unofficial
 * [simple-justwatch-python-api](https://github.com/Electronic-Mango/simple-justwatch-python-api)
 * `examples/providers_output.py` (GraphQL `packages` query for US).
 *
 * **Not authoritative:** JustWatch adds/removes services; use
 * `GET /api/discovery/streaming/providers?country=XX` for live codes per country.
 *
 * @module partnerProviderTerms.us
 */

export interface PartnerProviderTerm {
  /** GraphQL / package filter id (often matches Partner `technical_name`). */
  technicalName: string
  /** Short code used in URLs and many filters (Partner `short_name`). */
  shortName: string
  /** Human-readable service name for this snapshot (Partner `clear_name` / display). */
  clearName: string
}

/** US provider terms (416 entries). */
export const PARTNER_PROVIDER_TERMS_US: readonly PartnerProviderTerm[] = [
  { technicalName: "netflix", shortName: "nfx", clearName: "Netflix" },
  { technicalName: "amazonprime", shortName: "amp", clearName: "Amazon Prime Video" },
  { technicalName: "appletvplus", shortName: "atp", clearName: "Apple TV" },
  { technicalName: "disneyplus", shortName: "dnp", clearName: "Disney Plus" },
  { technicalName: "hulu", shortName: "hlu", clearName: "Hulu" },
  { technicalName: "mlsseasonpass", shortName: "mls", clearName: "MLS on Apple TV" },
  { technicalName: "amazon", shortName: "amz", clearName: "Amazon Video" },
  { technicalName: "itunes", shortName: "itu", clearName: "Apple TV Store" },
  { technicalName: "crunchyroll", shortName: "cru", clearName: "Crunchyroll" },
  { technicalName: "fubotv", shortName: "fuv", clearName: "fuboTV" },
  { technicalName: "max", shortName: "mxx", clearName: "HBO Max" },
  { technicalName: "amazonhbomax", shortName: "aho", clearName: "HBO Max Amazon Channel" },
  { technicalName: "amazonepix", shortName: "aep", clearName: "MGM+ Amazon Channel" },
  { technicalName: "amazoncrunchyroll", shortName: "cra", clearName: "Crunchyroll Amazon Channel" },
  { technicalName: "paramountpluspremium", shortName: "ppp", clearName: "Paramount Plus Premium" },
  { technicalName: "paramountplusessential", shortName: "ppe", clearName: "Paramount Plus Essential" },
  { technicalName: "peacocktv", shortName: "pct", clearName: "Peacock Premium" },
  { technicalName: "play", shortName: "ply", clearName: "Google Play Movies" },
  { technicalName: "youtube", shortName: "yot", clearName: "YouTube" },
  { technicalName: "appletvparamountplus", shortName: "ppa", clearName: "Paramount Plus Apple TV Channel" },
  { technicalName: "appletvstarz", shortName: "szt", clearName: "Starz Apple TV Channel" },
  { technicalName: "appletvamcplus", shortName: "aat", clearName: "AMC Plus Apple TV Channel" },
  { technicalName: "appletvbritbox", shortName: "bba", clearName: "Britbox Apple TV Channel" },
  { technicalName: "f1appletv", shortName: "af1", clearName: "F1 on Apple TV" },
  { technicalName: "amazonparamountplus", shortName: "app", clearName: "Paramount+ Amazon Channel" },
  { technicalName: "amazondiscoveryplus", shortName: "adp", clearName: "Discovery+ Amazon Channel" },
  { technicalName: "amazonamcplus", shortName: "azp", clearName: "AMC+ Amazon Channel" },
  { technicalName: "rokuchannel", shortName: "rkc", clearName: "The Roku Channel" },
  { technicalName: "rokuchannelstarz", shortName: "sru", clearName: "Starz Roku Premium Channel" },
  { technicalName: "rokuchannelamcplus", shortName: "ark", clearName: "AMC+ Roku Premium Channel" },
  { technicalName: "amcplus", shortName: "acp", clearName: "AMC+" },
  { technicalName: "rokuchannelepix", shortName: "erk", clearName: "MGM Plus Roku Premium Channel" },
  { technicalName: "youtubered", shortName: "ytr", clearName: "YouTube Premium" },
  { technicalName: "thecw", shortName: "tcw", clearName: "The CW" },
  { technicalName: "kanopy", shortName: "knp", clearName: "Kanopy" },
  { technicalName: "hoopla", shortName: "hop", clearName: "Hoopla" },
  { technicalName: "vudu", shortName: "vdu", clearName: "Fandango At Home" },
  { technicalName: "youtubetv", shortName: "ytt", clearName: "YouTube TV" },
  { technicalName: "starz", shortName: "stz", clearName: "Starz" },
  { technicalName: "vudufree", shortName: "vuf", clearName: "Fandango at Home Free" },
  { technicalName: "criterionchannel", shortName: "crc", clearName: "Criterion Channel" },
  { technicalName: "pbs", shortName: "pbs", clearName: "PBS" },
  { technicalName: "fxnow", shortName: "fxn", clearName: "FXNow" },
  { technicalName: "justwatchtv", shortName: "jwt", clearName: "JustWatch TV" },
  { technicalName: "flixhouse", shortName: "fhs", clearName: "FlixHouse" },
  { technicalName: "sunnxt", shortName: "snx", clearName: "Sun Nxt" },
  { technicalName: "amc", shortName: "amc", clearName: "AMC" },
  { technicalName: "amctheatres", shortName: "amt", clearName: "AMC Theatres" },
  { technicalName: "fandor", shortName: "fnd", clearName: "Fandor" },
  { technicalName: "curiositystream", shortName: "cts", clearName: "Curiosity Stream" },
  { technicalName: "nbc", shortName: "nbc", clearName: "NBC" },
  { technicalName: "epix", shortName: "epx", clearName: "MGM Plus" },
  { technicalName: "freeform", shortName: "ffm", clearName: "Freeform" },
  { technicalName: "philo", shortName: "phl", clearName: "Philo" },
  { technicalName: "aetv", shortName: "aae", clearName: "A&E" },
  { technicalName: "lifetime", shortName: "lft", clearName: "Lifetime" },
  { technicalName: "shudder", shortName: "shd", clearName: "Shudder" },
  { technicalName: "acorntv", shortName: "act", clearName: "Acorn TV" },
  { technicalName: "sundancenow", shortName: "sdn", clearName: "Sundance Now" },
  { technicalName: "mubi", shortName: "mbi", clearName: "MUBI" },
  { technicalName: "guidedoc", shortName: "gdc", clearName: "GuideDoc" },
  { technicalName: "britbox", shortName: "bbo", clearName: "BritBox" },
  { technicalName: "netflixkids", shortName: "nfk", clearName: "Netflix Kids" },
  { technicalName: "umc", shortName: "umc", clearName: "ALLBLK" },
  { technicalName: "nbaleaguepass", shortName: "nlp", clearName: "NBA League Pass" },
  { technicalName: "historyvault", shortName: "hvt", clearName: "History Vault" },
  { technicalName: "rokuchannelparamountplus", shortName: "prk", clearName: "Paramount+ Roku Premium Channel" },
  { technicalName: "myoutdoortv", shortName: "mot", clearName: "MyOutdoorTV" },
  { technicalName: "wwenetwork", shortName: "wwe", clearName: "WWE Network" },
  { technicalName: "pureflix", shortName: "pux", clearName: "Pure Flix" },
  { technicalName: "lifetimemovieclub", shortName: "lmc", clearName: "Lifetime Movie Club" },
  { technicalName: "amazonpbskids", shortName: "apk", clearName: "PBS Kids Amazon Channel" },
  { technicalName: "amazoncinemax", shortName: "acn", clearName: "Cinemax Amazon Channel" },
  { technicalName: "amazonhallmarkmoviesnow", shortName: "ahm", clearName: "Hallmark+ Amazon Channel" },
  { technicalName: "amazonpbsmasterpiece", shortName: "apm", clearName: "PBS Masterpiece Amazon Channel" },
  { technicalName: "amazonmzchoice", shortName: "ame", clearName: "MZ Choice Amazon Channel" },
  { technicalName: "slingtv", shortName: "stv", clearName: "Sling TV Orange and Blue" },
  { technicalName: "plutotv", shortName: "ptv", clearName: "Pluto TV" },
  { technicalName: "byutv", shortName: "byu", clearName: "BYUtv" },
  { technicalName: "hidive", shortName: "hdv", clearName: "HiDive" },
  { technicalName: "vixtv", shortName: "vix", clearName: "VIX" },
  { technicalName: "nightflightplus", shortName: "nfp", clearName: "Night Flight Plus" },
  { technicalName: "dekkoo", shortName: "dkk", clearName: "Dekkoo" },
  { technicalName: "retrocrush", shortName: "rtc", clearName: "Retrocrush" },
  { technicalName: "shoutfactorytv", shortName: "sft", clearName: "Shout! Factory TV" },
  { technicalName: "ovid", shortName: "ovi", clearName: "OVID" },
  { technicalName: "chaiflicks", shortName: "chf", clearName: "Chai Flicks" },
  { technicalName: "mhzchoice", shortName: "mhz", clearName: "Mhz Choice" },
  { technicalName: "amazonshudder", shortName: "asd", clearName: "Shudder Amazon Channel" },
  { technicalName: "vicetv", shortName: "vtv", clearName: "Vice TV" },
  { technicalName: "amazonmubi", shortName: "amu", clearName: "MUBI Amazon Channel" },
  { technicalName: "amazonacorntv", shortName: "aac", clearName: "AcornTV Amazon Channel" },
  { technicalName: "amazonbritbox", shortName: "abb", clearName: "BritBox Amazon Channel" },
  { technicalName: "amazonfandor", shortName: "afa", clearName: "Fandor Amazon Channel" },
  { technicalName: "amazonscreambox", shortName: "asb", clearName: "Screambox Amazon Channel" },
  { technicalName: "amazonsundancenow", shortName: "asn", clearName: "Sundance Now Amazon Channel" },
  { technicalName: "adultswim", shortName: "ads", clearName: "Adult Swim" },
  { technicalName: "usanetwork", shortName: "usn", clearName: "USA Network" },
  { technicalName: "flixfling", shortName: "fxf", clearName: "FlixFling" },
  { technicalName: "youtubefree", shortName: "yfr", clearName: "YouTube Free" },
  { technicalName: "amazonbetplus", shortName: "bpc", clearName: "Bet+ Amazon Channel" },
  { technicalName: "viki", shortName: "vik", clearName: "Rakuten Viki" },
  { technicalName: "tcm", shortName: "tcm", clearName: "TCM" },
  { technicalName: "bravotv", shortName: "brv", clearName: "Bravo TV" },
  { technicalName: "tnt", shortName: "tnt", clearName: "TNT" },
  { technicalName: "foodnetwork", shortName: "fnw", clearName: "Food Network" },
  { technicalName: "bbcamerica", shortName: "bca", clearName: "BBC America" },
  { technicalName: "indieflix", shortName: "ind", clearName: "IndieFlix" },
  { technicalName: "tlc", shortName: "tlc", clearName: "TLC" },
  { technicalName: "vimeo", shortName: "vio", clearName: "Vimeo" },
  { technicalName: "hgtv", shortName: "hgt", clearName: "HGTV" },
  { technicalName: "investigationdiscovery", shortName: "inv", clearName: "Investigation Discovery" },
  { technicalName: "sciencechannel", shortName: "sci", clearName: "Science Channel" },
  { technicalName: "animalplanet", shortName: "apl", clearName: "Animal Planet" },
  { technicalName: "discoverygo", shortName: "dis", clearName: "Discovery" },
  { technicalName: "travelchannel", shortName: "tra", clearName: "Travel Channel" },
  { technicalName: "heretv", shortName: "hrv", clearName: "Here TV" },
  { technicalName: "vh1", shortName: "vho", clearName: "VH1" },
  { technicalName: "amazondreamworkstv", shortName: "adw", clearName: "DreamWorksTV Amazon Channel" },
  { technicalName: "flixpremiere", shortName: "fpm", clearName: "Flix Premiere" },
  { technicalName: "tbs", shortName: "tus", clearName: "TBS" },
  { technicalName: "asiancrush", shortName: "asc", clearName: "AsianCrush" },
  { technicalName: "docsville", shortName: "dsv", clearName: "DOCSVILLE" },
  { technicalName: "revry", shortName: "rvy", clearName: "Revry" },
  { technicalName: "spectrumondemand", shortName: "sod", clearName: "Spectrum On Demand" },
  { technicalName: "hiyah", shortName: "hyh", clearName: "Hi-YAH" },
  { technicalName: "trutv", shortName: "tru", clearName: "tru TV" },
  { technicalName: "disneynow", shortName: "dnw", clearName: "DisneyNOW" },
  { technicalName: "wetv", shortName: "wet", clearName: "WeTV" },
  { technicalName: "plex", shortName: "plx", clearName: "Plex" },
  { technicalName: "plexfast", shortName: "plf", clearName: "Plex Live TV" },
  { technicalName: "wowpresentsplus", shortName: "wow", clearName: "WOW Presents Plus" },
  { technicalName: "plexplayer", shortName: "pxp", clearName: "Plex Player" },
  { technicalName: "magellantv", shortName: "mgl", clearName: "Magellan TV" },
  { technicalName: "justwatchplexchannel", shortName: "plc", clearName: "Plex Channel" },
  { technicalName: "broadwayhd", shortName: "bhd", clearName: "BroadwayHD" },
  { technicalName: "own", shortName: "own", clearName: "The Oprah Winfrey Network" },
  { technicalName: "filmzie", shortName: "fmz", clearName: "Filmzie" },
  { technicalName: "truestory", shortName: "trs", clearName: "True Story" },
  { technicalName: "moviesaints", shortName: "mvt", clearName: "MovieSaints" },
  { technicalName: "marthastewart", shortName: "mst", clearName: "Martha Stewart TV" },
  { technicalName: "dafilms", shortName: "daf", clearName: "DocAlliance Films" },
  { technicalName: "ondemandkorea", shortName: "kor", clearName: "OnDemandKorea" },
  { technicalName: "hoichoi", shortName: "hoc", clearName: "Hoichoi" },
  { technicalName: "darkroom", shortName: "drk", clearName: "Darkroom" },
  { technicalName: "iqiyi", shortName: "iqi", clearName: "iQIYI" },
  { technicalName: "metrograph", shortName: "mtg", clearName: "Metrograph" },
  { technicalName: "amazonimdbtv", shortName: "aim", clearName: "Amazon Prime Video Free with Ads" },
  { technicalName: "publicdomainmovies", shortName: "pdm", clearName: "Public Domain Movies" },
  { technicalName: "eternalfamily", shortName: "etf", clearName: "Eternal Family" },
  { technicalName: "fawesometv", shortName: "faw", clearName: "Fawesome" },
  { technicalName: "cultpix", shortName: "ctx", clearName: "Cultpix" },
  { technicalName: "eventive", shortName: "eve", clearName: "Eventive" },
  { technicalName: "filmbox", shortName: "flb", clearName: "FilmBox+" },
  { technicalName: "aha", shortName: "aha", clearName: "aha" },
  { technicalName: "amazonshorts", shortName: "atv", clearName: "ShortsTV Amazon Channel" },
  { technicalName: "espn", shortName: "esp", clearName: "ESPN" },
  { technicalName: "f1tv", shortName: "f1t", clearName: "F1TV Pro" },
  { technicalName: "nflplus", shortName: "nfl", clearName: "NFL Plus" },
  { technicalName: "espn2", shortName: "es2", clearName: "ESPN 2" },
  { technicalName: "espn3", shortName: "es3", clearName: "ESPN 3" },
  { technicalName: "espndeportes", shortName: "esd", clearName: "ESPN Deportes" },
  { technicalName: "espnplus", shortName: "epp", clearName: "ESPN Plus" },
  { technicalName: "mlbtv", shortName: "mlb", clearName: "MLB TV" },
  { technicalName: "takflix", shortName: "tak", clearName: "Takflix" },
  { technicalName: "tennischannel", shortName: "ten", clearName: "Tennis Channel" },
  { technicalName: "klassiki", shortName: "kls", clearName: "Klassiki" },
  { technicalName: "foxsports1", shortName: "fs1", clearName: "Fox Sports 1" },
  { technicalName: "dazn", shortName: "dzn", clearName: "DAZN" },
  { technicalName: "nhlnetwork", shortName: "nhn", clearName: "NHL Network" },
  { technicalName: "twitch", shortName: "twc", clearName: "Twitch" },
  { technicalName: "amazonstarz", shortName: "saz", clearName: "Starz Amazon Channel" },
  { technicalName: "netflixbasicwithads", shortName: "nfa", clearName: "Netflix Standard with Ads" },
  { technicalName: "foxsports", shortName: "fsp", clearName: "Fox Sports" },
  { technicalName: "slingtvorange", shortName: "slo", clearName: "Sling TV Orange" },
  { technicalName: "slingtvblue", shortName: "slb", clearName: "Sling TV Blue" },
  { technicalName: "amazoncohen", shortName: "ace", clearName: "Cohen Media Amazon Channel" },
  { technicalName: "florugby", shortName: "flo", clearName: "Flo Rugby" },
  { technicalName: "youtubesports", shortName: "yts", clearName: "YouTube Sports" },
  { technicalName: "courtside1891", shortName: "csd", clearName: "Courtside 1891" },
  { technicalName: "tennistv", shortName: "tnn", clearName: "Tennis TV" },
  { technicalName: "amazonvixplus", shortName: "avp", clearName: "ViX Premium Amazon Channel" },
  { technicalName: "amazonmlbtv", shortName: "apb", clearName: "MLB.TV Amazon Channel" },
  { technicalName: "amazonnbatv", shortName: "ant", clearName: "NBA TV Amazon Channel" },
  { technicalName: "amazonnbalp", shortName: "anb", clearName: "NBA League Pass Amazon Channel" },
  { technicalName: "runtime", shortName: "run", clearName: "Runtime" },
  { technicalName: "mlbnetwork", shortName: "mln", clearName: "MLB Network" },
  { technicalName: "slingsportsextra", shortName: "sse", clearName: "Sling TV Sports Extras" },
  { technicalName: "fandango", shortName: "fad", clearName: "Fandango" },
  { technicalName: "ballysports", shortName: "bsp", clearName: "Bally Sports" },
  { technicalName: "beinsports", shortName: "bei", clearName: "beIN SPORTS" },
  { technicalName: "foxsports2", shortName: "fs2", clearName: "Fox Sports 2" },
  { technicalName: "willowtv", shortName: "wil", clearName: "WILLOW" },
  { technicalName: "telemundous", shortName: "tlm", clearName: "Telemundo" },
  { technicalName: "discoveryplusus", shortName: "dpu", clearName: "Discovery +" },
  { technicalName: "nflsundayticket", shortName: "nst", clearName: "NFL Sunday Ticket" },
  { technicalName: "ovationtv", shortName: "ovt", clearName: "Ovation TV" },
  { technicalName: "angel", shortName: "agl", clearName: "Angel Studios" },
  { technicalName: "cineverse", shortName: "cnv", clearName: "Cineverse" },
  { technicalName: "adtv", shortName: "adt", clearName: "AD tv" },
  { technicalName: "midnightpulp", shortName: "mnp", clearName: "Midnight Pulp" },
  { technicalName: "fyi", shortName: "fyi", clearName: "FYI Network" },
  { technicalName: "xumoplay", shortName: "xum", clearName: "Xumo Play" },
  { technicalName: "nationalgeographic", shortName: "nag", clearName: "National Geographic" },
  { technicalName: "atomtickets", shortName: "ati", clearName: "Atom Tickets" },
  { technicalName: "shahidvip", shortName: "sha", clearName: "Shahid VIP" },
  { technicalName: "distrotv", shortName: "dst", clearName: "DistroTV" },
  { technicalName: "myfilmfriend", shortName: "mff", clearName: "myfilmfriend" },
  { technicalName: "cinemark", shortName: "cmk", clearName: "Cinemark" },
  { technicalName: "outsideonline", shortName: "oow", clearName: "Outside Watch" },
  { technicalName: "cinepoliscinema", shortName: "cnu", clearName: "Cinepolis Cinemas" },
  { technicalName: "fanatiz", shortName: "ftz", clearName: "Fanatiz" },
  { technicalName: "nbalpyoutube", shortName: "nyt", clearName: "NBA League Pass on YouTube TV" },
  { technicalName: "amazonfullmoon", shortName: "afm", clearName: "Full Moon Amazon Channel" },
  { technicalName: "fifaplus", shortName: "fif", clearName: "FIFA+" },
  { technicalName: "univervideo", shortName: "unv", clearName: "Univer Video" },
  { technicalName: "glewed", shortName: "gwd", clearName: "GlewedTV" },
  { technicalName: "foxdeportes", shortName: "fxd", clearName: "Fox Deportes" },
  { technicalName: "dfbplay", shortName: "dfb", clearName: "DFB Play" },
  { technicalName: "toongoggles", shortName: "tgl", clearName: "Toon Goggles" },
  { technicalName: "appletvaetncrimecentral", shortName: "aec", clearName: "A&E Crime Central Apple TV Channel" },
  { technicalName: "appletvacorntv", shortName: "acr", clearName: "Acorn TV Apple TV" },
  { technicalName: "appletvumc", shortName: "alb", clearName: "ALLBLK Apple TV channel" },
  { technicalName: "appletvupfaithfamily", shortName: "ufa", clearName: "UP Faith & Family Apple TV Channel" },
  { technicalName: "appletvtastemade", shortName: "tma", clearName: "Tastemade Apple TV Channel" },
  { technicalName: "appletvsundancenow", shortName: "sap", clearName: "Sundance Now Apple TV Channel" },
  { technicalName: "appletvshudder", shortName: "sua", clearName: "Shudder Apple TV Channel" },
  { technicalName: "appletvscreenpix", shortName: "sxa", clearName: "ScreenPix Apple TV Channel" },
  { technicalName: "appletvouttv", shortName: "oua", clearName: "OUTtv Apple TV Channel" },
  { technicalName: "appletvlifetimemovieclub", shortName: "lma", clearName: "Lifetime Movie Club Apple TV Channel" },
  { technicalName: "appletvhallmarkmoviesnow", shortName: "hmc", clearName: "Hallmark+ Apple TV Channel" },
  { technicalName: "appletverosnow", shortName: "ena", clearName: "Eros Now Select Apple TV Channel" },
  { technicalName: "appletvcuriositystreamstandard", shortName: "csa", clearName: "CuriosityStream Apple TV Channel" },
  { technicalName: "appletvcinemax", shortName: "cma", clearName: "Cinemax Apple TV Channel" },
  { technicalName: "appletvbbcselect", shortName: "bsa", clearName: "BBC Select Apple Tv channel" },
  { technicalName: "appletvbetplus", shortName: "bpa", clearName: "BET+  Apple TV channel" },
  { technicalName: "appletvcarnegiehallplus", shortName: "cha", clearName: "Carnegie Hall+ Apple TV Channel" },
  { technicalName: "appletvifcunlimited", shortName: "ifc", clearName: "IFC Films Unlimited Apple TV Channel" },
  { technicalName: "appletvhistoryvault", shortName: "hva", clearName: "HISTORY Vault Apple TV Channel" },
  { technicalName: "benficatv", shortName: "ben", clearName: "BTV" },
  { technicalName: "amazonhistoryvault", shortName: "ahv", clearName: "HISTORY Vault Amazon Channel" },
  { technicalName: "amazoncarnegiehallplus", shortName: "cgh", clearName: "Carnegie Hall+ Amazon Channel" },
  { technicalName: "amazonlifetimemovieclub", shortName: "lia", clearName: "Lifetime Movie Club Amazon Channel" },
  { technicalName: "filmmovementplus", shortName: "fmp", clearName: "Film Movement Plus" },
  { technicalName: "nwslsoccercom", shortName: "nws", clearName: "NWSL+" },
  { technicalName: "euroleaguetv", shortName: "elt", clearName: "EuroLeague TV" },
  { technicalName: "cricbuzz", shortName: "cbz", clearName: "Cricbuzz" },
  { technicalName: "amazonprimevideowithads", shortName: "pva", clearName: "Amazon Prime Video with Ads" },
  { technicalName: "tromanow", shortName: "trn", clearName: "Troma NOW" },
  { technicalName: "joltfilm", shortName: "jfl", clearName: "Jolt Film" },
  { technicalName: "abcgo", shortName: "abc", clearName: "ABC" },
  { technicalName: "regalcinemas", shortName: "reg", clearName: "Regal Cinemas" },
  { technicalName: "harkinstheaters", shortName: "hrk", clearName: "Harkins Theatres" },
  { technicalName: "bbtheatres", shortName: "bbt", clearName: "B&B Theatres" },
  { technicalName: "marcustheatres", shortName: "mrc", clearName: "Marcus Theatres" },
  { technicalName: "kinofilmcollection", shortName: "kif", clearName: "Kino Film Collection" },
  { technicalName: "plutotvfast", shortName: "ptl", clearName: "Pluto TV Live" },
  { technicalName: "cineversefast", shortName: "clt", clearName: "Cineverse LiveTV" },
  { technicalName: "amazonstrandreleasing", shortName: "ars", clearName: "Strand Releasing Amazon Channel" },
  { technicalName: "peacocktvpremium", shortName: "pcp", clearName: "Peacock Premium Plus" },
  { technicalName: "univisionnow", shortName: "unw", clearName: "Univision NOW" },
  { technicalName: "amazonumc", shortName: "abk", clearName: "ALLBLK Amazon channel" },
  { technicalName: "nflnetwork", shortName: "nfn", clearName: "NFL Network" },
  { technicalName: "therugbynetwork", shortName: "rnk", clearName: "The Rugby Network" },
  { technicalName: "amazonappletvplus", shortName: "avl", clearName: "Apple TV Amazon Channel" },
  { technicalName: "amazonmotorvision", shortName: "amv", clearName: "Motorvision TV Amazon Channel" },
  { technicalName: "amazonstingrayclassica", shortName: "scl", clearName: "Stingray Classica Amazon Channel" },
  { technicalName: "amazonstingraydjazz", shortName: "adz", clearName: "Stingray Djazz Amazon Channel" },
  { technicalName: "amazonstingraykaraoke", shortName: "skk", clearName: "Stingray Karaoke Amazon Channel" },
  { technicalName: "amazonacaciatv", shortName: "acv", clearName: "Acaciatv Amazon Channel" },
  { technicalName: "amazonalchemiya", shortName: "aal", clearName: "Alchemiya Amazon Channel" },
  { technicalName: "amazonallwarriornetwork", shortName: "awn", clearName: "All warrior network Amazon Channel" },
  { technicalName: "amazonamebatv", shortName: "abt", clearName: "Amebatv Amazon Channel" },
  { technicalName: "amazonaspiretv", shortName: "apt", clearName: "Aspire TV Amazon Channel" },
  { technicalName: "amazonbefit", shortName: "bft", clearName: "BeFit Amazon Channel" },
  { technicalName: "amazonbestevertv", shortName: "bst", clearName: "Best tv ever Amazon Channel" },
  { technicalName: "amazonbestofbritish", shortName: "bob", clearName: "Best of British Tv Amazon Channel" },
  { technicalName: "amazonbaeble", shortName: "bbl", clearName: "Baeble Amazon Channel" },
  { technicalName: "amazonbestwesternsever", shortName: "bwa", clearName: "Best Westerns Ever Amazon Channel" },
  { technicalName: "amazonbroadwayhd", shortName: "bha", clearName: "Broadway HD Amazon Channel" },
  { technicalName: "amazonbrownsugar", shortName: "abs", clearName: "Brown Sugar Amazon Channel" },
  { technicalName: "amazonbfiplayer", shortName: "abf", clearName: "BFI Player Amazon Channel" },
  { technicalName: "kleaguetv", shortName: "kl1", clearName: "K League TV" },
  { technicalName: "amazoncodacollection", shortName: "ccl", clearName: "The Coda Collection Amazon Channel" },
  { technicalName: "amazoncontv", shortName: "mtp", clearName: "Midnight Pulp Amazon Channel" },
  { technicalName: "amazondailyburn", shortName: "dba", clearName: "Daily Burn Amazon Channel" },
  { technicalName: "amazondaringdocs", shortName: "dda", clearName: "Daring Docs Amazon Channel" },
  { technicalName: "amazondekkoo", shortName: "dka", clearName: "Dekkoo Amazon Channel" },
  { technicalName: "amazondoccom", shortName: "dom", clearName: "DocCom Amazon Channel" },
  { technicalName: "amazondocuramafilms", shortName: "dfa", clearName: "DocuramaFilms Amazon Channel" },
  { technicalName: "amazondove", shortName: "dva", clearName: "Dove Amazon Channel" },
  { technicalName: "amazondox", shortName: "dox", clearName: "Dox Amazon Channel" },
  { technicalName: "amazonfanduelsports", shortName: "fsn", clearName: "FanDuel Sports Network Amazon Channel" },
  { technicalName: "amazonwillowtv", shortName: "wtc", clearName: "Willow TV Amazon Channel" },
  { technicalName: "amazonhidive", shortName: "hda", clearName: "Hidive Amazon Channel" },
  { technicalName: "amazonechoboom", shortName: "eba", clearName: "Echoboom Amazon Channel" },
  { technicalName: "amazonelgourmet", shortName: "coa", clearName: "Cocina ON Amazon Channel" },
  { technicalName: "amazonfearfactory", shortName: "ffa", clearName: "Fear Factory Amazon Channel" },
  { technicalName: "amazonfilmmovement", shortName: "flm", clearName: "Film Movement Plus Amazon Channel" },
  { technicalName: "amazonfitfusion", shortName: "fna", clearName: "Fitfusion Amazon Channel" },
  { technicalName: "amazonflixlatino", shortName: "fxa", clearName: "FlixLatino Amazon Channel" },
  { technicalName: "amazonfoodmatters", shortName: "foa", clearName: "Food Matters Amazon Channel" },
  { technicalName: "amazonfuse", shortName: "afs", clearName: "Fuse+ Amazon Channel" },
  { technicalName: "amazongrokker", shortName: "gka", clearName: "Grokker Yoga & Fitness Amazon Channel" },
  { technicalName: "amazonhiyah", shortName: "hya", clearName: "Hi-YAH Amazon Channel" },
  { technicalName: "amazonindieclub", shortName: "ica", clearName: "Indie Club Amazon Channel" },
  { technicalName: "amazonindieflix", shortName: "inx", clearName: "IndieFlix Shorts Amazon Channel" },
  { technicalName: "amazonheretv", shortName: "hta", clearName: "Here TV  Amazon Channel" },
  { technicalName: "amazonfilmbox", shortName: "afb", clearName: "FilmBox Live Amazon Channel" },
  { technicalName: "amazonhopster", shortName: "ahs", clearName: "Hopster Amazon Channel" },
  { technicalName: "amazongaia", shortName: "aga", clearName: "Gaia Amazon Channel" },
  { technicalName: "amazonfrancechannel", shortName: "afc", clearName: "France Channel Amazon Channel" },
  { technicalName: "amazonindiepix", shortName: "ipx", clearName: "IndiePix Unlimited Amazon Channel" },
  { technicalName: "amazonjedge", shortName: "dok", clearName: "Doki Amazon Channel" },
  { technicalName: "amazonkcpglobal", shortName: "kca", clearName: "Kocowa Amazon Channel" },
  { technicalName: "amazonkidgenius", shortName: "ktc", clearName: "Kartoon Channel Amazon Channel" },
  { technicalName: "amazonkidstream", shortName: "kda", clearName: "Kidstream Amazon Channel" },
  { technicalName: "amazonkinofilmcollection", shortName: "kfc", clearName: "Kino Film Collection Amazon Channel" },
  { technicalName: "amazonmagnolianetwork", shortName: "amn", clearName: "Magnolia Network Amazon Channel" },
  { technicalName: "amazonmagnoliaselects", shortName: "msa", clearName: "Magnolia Selects Amazon Channel" },
  { technicalName: "amazonmandn", shortName: "mna", clearName: "Monsters and Nightmares Amazon Channel" },
  { technicalName: "amazonmarqueetv", shortName: "mqa", clearName: "Marquee TV Amazon Channel" },
  { technicalName: "amazonmhzchoice", shortName: "mha", clearName: "MHz Choice Amazon Channel" },
  { technicalName: "amazonmotv", shortName: "myo", clearName: "MyOutdoor TV Amazon Channel" },
  { technicalName: "amazonoutside", shortName: "out", clearName: "Outside TV Features Amzon Channel" },
  { technicalName: "amazonpannacooking", shortName: "pca", clearName: "Panna Cooking Amazon Channel" },
  { technicalName: "amazonpassionflix", shortName: "pfa", clearName: "Passionflix Amazon Channel" },
  { technicalName: "amazonpbo", shortName: "pbo", clearName: "Pinoy Box Office Amazon Channel" },
  { technicalName: "amazonpbsamerica", shortName: "pbm", clearName: "PBS America Amazon Channel" },
  { technicalName: "amazonpbsdoc", shortName: "pbd", clearName: "PBS Documentaries Amazon Channel" },
  { technicalName: "amazonpbsliving", shortName: "pbl", clearName: "PBS Living Amazon Channel" },
  { technicalName: "amazonpixl", shortName: "pxl", clearName: "PixL Amazon Channel" },
  { technicalName: "amazonpureflix", shortName: "gpx", clearName: "Great American Pure Flix Amazon Channel" },
  { technicalName: "amazonreelz", shortName: "rla", clearName: "REELZ+ Amazon Channel" },
  { technicalName: "amazonrevry", shortName: "rya", clearName: "Revry Amazon Channel" },
  { technicalName: "amazonryanfriends", shortName: "rfp", clearName: "Ryan and Friends Plus Amazon Channel" },
  { technicalName: "amazonsensical", shortName: "ssl", clearName: "Sensical Amazon Channel" },
  { technicalName: "amazonstingrayzenlife", shortName: "zls", clearName: "ZenLIFE by Stingray Amazon Channel" },
  { technicalName: "amazonsweatflix", shortName: "swf", clearName: "Sweatflix Amazon Channel" },
  { technicalName: "amazontheafricachannel", shortName: "afr", clearName: "Demand Africa Amazon Channel" },
  { technicalName: "amazonthesurfnetwork", shortName: "tsf", clearName: "The Surf Network Amazon Channel" },
  { technicalName: "amazontoku", shortName: "atu", clearName: "Toku Amazon Channel" },
  { technicalName: "amazontribecashortlist", shortName: "mse", clearName: "MovieSphere+ Amazon Channel" },
  { technicalName: "amazontrueroyalty", shortName: "try", clearName: "True Royalty Amazon Channel" },
  { technicalName: "amazonvaporvue", shortName: "ful", clearName: "FUEL TV+ Amazon Channel" },
  { technicalName: "amazonvdpaerus0y42p3p9a56", shortName: "aer", clearName: "AeroCinema Amazon Channel" },
  { technicalName: "amazonvdpbonus0sqqdwawqj0", shortName: "bfx", clearName: "BongFlix Amazon Channel" },
  { technicalName: "amazonvdpdesus4rwr3y4v0sv", shortName: "dit", clearName: "Destiny Image TV Amazon Channel" },
  { technicalName: "amazonvdpdreusc2tcmc9g3xj", shortName: "dsk", clearName: "Dreamscape Kids Amazon Channel" },
  { technicalName: "amazonvdpfidusatrhcwdch2v", shortName: "fdt", clearName: "FidoTV Channel Amazon Channel" },
  { technicalName: "amazonvdpgreusmcewhet31wq", shortName: "gps", clearName: "Green Planet Stream Amazon Channel" },
  { technicalName: "amazonvdpkunuspd97qw8aw6f", shortName: "kyt", clearName: "Kundalini Yoga TV Amazon Channel" },
  { technicalName: "amazonvdpleausek27fnk8074", shortName: "lhr", clearName: "Learn How to Run Amzon Channel" },
  { technicalName: "amazonvdpsleustp3c4418sz1", shortName: "ssm", clearName: "Sleep Sounds & Meditation Amazon Channel" },
  { technicalName: "amazonvdptheusa095c5yr1ny", shortName: "ttc", clearName: "The Titanic Channel Amazon Channel" },
  { technicalName: "amazonvdpwatuspt801mb64mm", shortName: "wkd", clearName: "Watchit.Kid Amazon Channel" },
  { technicalName: "amazonvdpwelusy88tdt5nwq0", shortName: "wpp", clearName: "Wellness Plus by Psychetruth Amazon Channel" },
  { technicalName: "amazonvdpyogus499nnea7qm5", shortName: "yia", clearName: "Yoga International Amazon Channel" },
  { technicalName: "amazonvdpyoguse9vn6wa0s64", shortName: "yft", clearName: "Yoga and Fitness TV Amazon channel" },
  { technicalName: "amazonvdpyogusg2yt8npv2qe", shortName: "yda", clearName: "Yoga Download Amazon Channel" },
  { technicalName: "amazonvdpyouusc2pfakgjb6y", shortName: "yha", clearName: "Young Hollywood Amazon Channel" },
  { technicalName: "amazonvemoxcine", shortName: "vmc", clearName: "Vemox Cine Amazon Channel" },
  { technicalName: "amazonwag", shortName: "wag", clearName: "Warriors and Gangsters Amazon Channel" },
  { technicalName: "amazonxivetv", shortName: "xiv", clearName: "Xive TV Documentaries Amazon Channel" },
  { technicalName: "amazonxltv", shortName: "xlt", clearName: "XLTV Amazon Channel" },
  { technicalName: "amazonyippeetv", shortName: "ykt", clearName: "Yipee Kids TV Amazon Channel" },
  { technicalName: "amazonyogaanytime", shortName: "yat", clearName: "Yoga Anytime Amazon Channel" },
  { technicalName: "amazonplanetearth", shortName: "pea", clearName: "Planet Earth Amazon Channel" },
  { technicalName: "amazonitvplus", shortName: "ait", clearName: "ITV Amazon Channel" },
  { technicalName: "amazonshoutfactory", shortName: "asf", clearName: "Shout! Factory Amazon Channel" },
  { technicalName: "amazonpongalo", shortName: "apn", clearName: "Pongalo Amazon Channel" },
  { technicalName: "amazontvcortos", shortName: "atc", clearName: "TVCortos Amazon Channel" },
  { technicalName: "amazonupfaithfamily", shortName: "ufc", clearName: "UP Faith & Family Amazon Channel" },
  { technicalName: "amazontastemade", shortName: "tmm", clearName: "Tastemade Amazon Channel" },
  { technicalName: "amazonthegreatcourses", shortName: "atg", clearName: "The Great Courses Amazon Channel" },
  { technicalName: "amazonviaplay", shortName: "vpy", clearName: "Viaplay Amazon Channel" },
  { technicalName: "amazonqelloconcerts", shortName: "qcs", clearName: "Qello Concerts by Stingray Amazon Channel" },
  { technicalName: "foundtv", shortName: "fod", clearName: "FOUND TV" },
  { technicalName: "stupidco", shortName: "suc", clearName: "Stupid Co" },
  { technicalName: "amazongaiamtv", shortName: "gmt", clearName: "Gaiam TV Yoga & Fit" },
  { technicalName: "kocowa", shortName: "koc", clearName: "Kocowa" },
  { technicalName: "history", shortName: "his", clearName: "History" },
  { technicalName: "amazondanime", shortName: "dan", clearName: "dAnime Amazon Channel" },
  { technicalName: "amazonviewster", shortName: "avt", clearName: "RetroCrush Amazon Channel" },
  { technicalName: "amazonscreenpix", shortName: "sxc", clearName: "ScreenPix Amazon Channel" },
  { technicalName: "mometu", shortName: "mme", clearName: "Mometu" },
  { technicalName: "oxygen", shortName: "oxy", clearName: "OXYGEN" },
  { technicalName: "amazonkidsandfamilymax", shortName: "kfm", clearName: "Kids and Family Max amazon channel" },
  { technicalName: "appletvpantaya", shortName: "pap", clearName: "Pantaya appletv channel" },
  { technicalName: "foxone", shortName: "fxo", clearName: "FOX One" },
  { technicalName: "destinationcalcio", shortName: "dct", clearName: "Destination Calcio" },
  { technicalName: "amazonhallmark", shortName: "hma", clearName: "Hallmark TV Amazon Channel" },
  { technicalName: "amazonpeacockpremiumplus", shortName: "pep", clearName: "Peacock Premium Plus Amazon Channel" },
  { technicalName: "amazonfoxone", shortName: "f1a", clearName: "FOX One Amazon Channel" },
  { technicalName: "bloodstream", shortName: "bsm", clearName: "Bloodstream" },
  { technicalName: "arrowvideo", shortName: "avd", clearName: "Arrow Video" },
  { technicalName: "barnesandnoble", shortName: "bnb", clearName: "Barnes & Noble" },
  { technicalName: "zavvi", shortName: "zav", clearName: "Zavvi" },
  { technicalName: "movieme", shortName: "mvm", clearName: "MovieMe" },
  { technicalName: "gruv", shortName: "grv", clearName: "GRUV" },
  { technicalName: "amazondvdbr", shortName: "adb", clearName: "Amazon DVD / Blu-ray" },
  { technicalName: "amazondazn", shortName: "dza", clearName: "DAZN Amazon Channel" },
  { technicalName: "tubitv", shortName: "tbv", clearName: "Tubi TV" },
  { technicalName: "kableone", shortName: "kbo", clearName: "KableOne" },
  { technicalName: "kqed", shortName: "kqd", clearName: "KQED" },
  { technicalName: "thirteen", shortName: "thr", clearName: "Thirteen" },
  { technicalName: "wetaplus", shortName: "wtp", clearName: "WETA+" },
  { technicalName: "caixaforumplus", shortName: "cfp", clearName: "CaixaForum+" },
  { technicalName: "yowtv", shortName: "yow", clearName: "YOW.tv" },
  { technicalName: "amazonwonderproject", shortName: "awt", clearName: "Wonder Project Amazon Channel" },
  { technicalName: "artflix", shortName: "afx", clearName: "Artiflix" },
  { technicalName: "amazoncuriositystreamstandard", shortName: "acs", clearName: "CuriosityStream Amazon Channel" },
  { technicalName: "amazontennischannel", shortName: "tch", clearName: "Tennis Channel Amazon Channel" },
  { technicalName: "amasiantv", shortName: "aiv", clearName: "Amasian TV" },
  { technicalName: "tpt", shortName: "tpt", clearName: "TPT" },
  { technicalName: "artify", shortName: "atf", clearName: "Artify" },
]
