/**
 * Personalized suggestion prompts for the assistant
 * 
 * Suggestions are pre-generated by a scheduled job and stored in the database.
 * This endpoint simply retrieves the stored suggestions for the user.
 */
import type { FastifyInstance } from 'fastify'
import { queryOne } from '../../../lib/db.js'
import { requireAuth, type SessionUser } from '../../../plugins/auth.js'

interface SuggestionsRow {
  suggestions: string[]
}

const DEFAULT_SUGGESTIONS = [
  'What should I watch tonight?',
  'Show me my top picks',
  'Find me something like Inception',
  'What sci-fi movies do you recommend?',
]

export function registerSuggestionsHandler(fastify: FastifyInstance) {
  /**
   * GET /api/assistant/suggestions
   * Get pre-generated personalized suggestion prompts for the user
   */
  fastify.get('/api/assistant/suggestions', { preHandler: requireAuth, schema: { tags: ["ai-assistant"] } }, async (request, reply) => {
    const user = request.user as SessionUser

    try {
      // Get pre-generated suggestions from database
      const result = await queryOne<SuggestionsRow>(
        `SELECT suggestions FROM assistant_suggestions WHERE user_id = $1`,
        [user.id]
      )

      if (result && result.suggestions && result.suggestions.length > 0) {
        return reply.send({ suggestions: result.suggestions })
      }

      // Return default suggestions if none stored yet
      return reply.send({ suggestions: DEFAULT_SUGGESTIONS })
    } catch (err) {
      request.log.error({ err }, 'Failed to fetch suggestions')
      return reply.send({ suggestions: DEFAULT_SUGGESTIONS })
    }
  })
}

